security:


    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        # used to reload user from session & other features (e.g. switch_user)
        in_database:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            
            provider: in_database

            form_login:
                login_path: login
                check_path: login

            logout:
                path: logout
                target: login
        
            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        # matches /admin/users/*
        - { path: ^/pokemon, roles: ROLE_USER }
        - { path: ^/pokedex, roles: ROLE_USER }
        - { path: ^/changePassword, roles: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/indo, roles: ROLE_USER }

        # matches /admin/* except for anything matching the above rule
        - { path: ^/settings, roles: ROLE_ADMIN }

    